version: "2.1"

services:
    odoo$ODOO_MAJOR:
        extends:
            file: common.yaml
            service: odoo
        build:
            args:
                # To aggregate in development, use `setup-devel.yaml`
                AGGREGATE: "no"
                # No need for this in development
                PYTHONOPTIMIZE: 0
                PIP_INSTALL_ODOO: "no"
                CLEAN: "no"
                COMPILE: "no"
                # You want demo data for development
                WITHOUT_DEMO: "no"
        ports:
            - "127.0.0.1:${ODOO_MAJOR}069:8069"
            - "127.0.0.1:${ODOO_MAJOR}072:8072"
        volumes:
            - ./odoo/custom:/opt/odoo/custom:ro,z
        environment:
            PGDATABASE: devel
            # Don't optimize in development
            PYTHONOPTIMIZE: 0
        links:
            - db$ODOO_MAJOR:db
            - inbox
            - smtp
            - wdb
        # Uncomment to start in unit test mode, add module names if you wish
        # command: unittest module1,module2
        command: odoo --dev all

    db$ODOO_MAJOR:
        extends:
            file: common.yaml
            service: db

    inbox:
        extends:
            file: common.yaml
            service: inboxfake

    smtp:
        extends:
            file: common.yaml
            service: smtpfake

    wdb:
        image: yajo/wdb-server
        ports:
            - "127.0.0.1:1984:1984"

volumes:
    filestore$ODOO_MAJOR:
    db$ODOO_MAJOR:
