version: "2.1"

services:
    odoo:
        extends:
            file: common.yaml
            service: odoo
        build:
            args:
                PGDATABASE: devel
                # To aggregate in development, use `setup-devel.yaml`
                AGGREGATE: "no"
                # No need for this in development
                PYTHONOPTIMIZE: 0
                PIP_INSTALL_ODOO: "no"
                CLEAN: "no"
                COMPILE: "no"
                # You want demo data for development
                WITHOUT_DEMO: "no"
        ports:
            - "127.0.0.1:${ODOO_MAJOR}069:8069"
            - "127.0.0.1:${ODOO_MAJOR}072:8072"
        volumes:
            - ./odoo/custom:/opt/odoo/custom:ro,z
        command: odoo --dev all

    db:
        extends:
            file: common.yaml
            service: db

    inbox:
        extends:
            file: common.yaml
            service: inboxfake

    smtp:
        extends:
            file: common.yaml
            service: smtpfake

    wdb:
        image: yajo/wdb-server
        ports:
            - "127.0.0.1:1984:1984"

volumes:
    filestore10:
    db10:
