version: "3.1"

services:
    odoo:
        build:
            context: ./odoo
            args:
                PGUSER: "$DB_USER"
                PGPASSWORD: "$DB_PASSWORD"
                PGDATABASE: devel
                # To aggregate in development, use `setup-devel.yaml`
                AGGREGATE: "false"
                # No need for this in development
                PYTHONOPTIMIZE: 0
                PIP_INSTALL_ODOO: "false"
                CLEAN: "false"
                COMPILE: "false"
                # You want demo data for development
                WITHOUT_DEMO: "false"
        tty: true
        ports:
            - "127.0.0.1:${ODOO_MAJOR}069:8069"
            - "127.0.0.1:${ODOO_MAJOR}072:8072"
            - "127.0.0.1:6899:6899"
        volumes:
            - filestore$ODOO_MAJOR:/var/lib/odoo
            - ./odoo/custom:/opt/odoo/custom:ro,z
        depends_on:
            - db
            - smtp
            - inbox
            - wdb
        command: odoo --workers 0 --dev all

    db:
        image: postgres:${DB_VERSION}-alpine
        environment:
            POSTGRES_USER: "$DB_USER"
            POSTGRES_PASSWORD: "$DB_PASSWORD"
        volumes:
            - db$ODOO_MAJOR:/var/lib/postgresql/data

    inbox:
        image: tecnativa/tcp-proxy
        environment:
            LISTEN: "$INBOX_FAKE_LISTEN"
            TALK: "$INBOX_FAKE_TALK"

    smtp:
        image: tecnativa/smtp-sink

    wdb:
        image: yajo/wdb-server
        ports:
            - "127.0.0.1:1984:1984"

volumes:
    # XXX Odoo volume names must match $ODOO_MAJOR for quick branch switching
    filestore10:
    db10:
