version: "2.1"
services:
    odoo10:
        extends:
            file: common.yaml
            service: odoo
        restart: always
        environment:
            ADMIN_PASSWORD: example secure password
        links:
            - db10:db
        volumes:
            - filestore10:/home/odoo/.local/share/Odoo

    db10:
        extends:
            file: common.yaml
            service: db
        restart: always
        volumes:
            - db10:/var/lib/postgresql/data

    https:
        build: https
        restart: always
        ports:
            - "80:80"
            - "443:443"
        links:
            - odoo10:www
        volumes:
            - certs:/etc/letsencrypt
            - certscron:/var/spool/cron/cronstamps
        environment:
            PORT: 8069
            # XXX Change these for your real data
            EMAIL: admin@example.com
            DOMAINS: example.com
            STAGING: "false"

    smtp:
        extends:
            file: common.yaml
            service: smtpreal

    backup:
        image: tecnativa/server-backup
        environment:
            # XXX Fill all of these according to your settings
            ROOT_EMAIL_FROM: backup@example.com
            ROOT_EMAIL_TO: alerts@example.com
            MAIL_RELAY_HOST: smtp
            BACKUP_S3_ACCESS_KEY: example key
            BACKUP_S3_SECRET_KEY: example secret
            BACKUP_S3_BUCKET: example-bkp
            BACKUP_S3_INSTANCE: docker-example
            BACKUP_SEND_MAIL_ERR: 1
            BACKUP_SEND_MAIL_LOG: 1
            BACKUP_EMAIL_SUBJECT: '[EXAMPLE]'
            BACKUP_EMAIL_FROM: backup@example.com
            BACKUP_EMAIL_TO: alerts@example.com
            BACKUP_ENCRYPT: 1
            BACKUP_ENCRYPT_KEY: example encryption key
            BACKUP_SOURCES: /home/odoo/.local/share/Odoo,0,1
            PG_USER: odoo
            PG_PASS: odoopassword
        links:
            - db10:postgresdb
            - smtp
        volumes_from:
            - odoo10data

volumes:
    filestore10:
    db10:
    smtp:
    certs:
    certscron:
