version: "2.1"
services:
    odoo:
        extends:
            file: common.yaml
            service: odoo
        build:
            args:
                ADMIN_PASSWORD: "$ODOO_ADMIN_PASSWORD"
                PROXY_MODE: "$ODOO_PROXY_MODE"
        restart: unless-stopped
        depends_on:
            - db
            - smtp
            - inbox

    db:
        extends:
            file: common.yaml
            service: db
        restart: unless-stopped

    https:
        extends:
            file: common.yaml
            service: https
        restart: unless-stopped
        environment:
            STAGING: "false"
        depends_on:
            - odoo

    inbox:
        extends:
            file: common.yaml
            service: inboxreal
        restart: unless-stopped

    smtp:
        extends:
            file: common.yaml
            service: smtpreal
        restart: unless-stopped

    backup:
        extends:
            file: common.yaml
            service: backup
        restart: unless-stopped
        volumes_from:
            - odoo
        depends_on:
            - odoo
            - db
            - smtp

volumes:
    # XXX Odoo volume names must match $ODOO_MAJOR for quick branch switching
    filestore10:
    db10:
    smtp:
    certs:
    certscron:
