version: "2.1"
services:
    odoo$ODOO_MAJOR:
        extends:
            file: common.yaml
            service: odoo
        bulid:
            args:
                ADMIN_PASSWORD: "$ODOO_ADMIN_PASSWORD"
                PROXY_MODE: "$ODOO_PROXY_MODE"
        restart: unless-stopped
        links:
            - db$ODOO_MAJOR:db
            - inbox
            - smtp
        networks:
            - back

    db$ODOO_MAJOR:
        extends:
            file: common.yaml
            service: db
        restart: unless-stopped
        networks:
            - back

    https:
        extends:
            file: common.yaml
            service: https
        links:
            - odoo$ODOO_MAJOR:www
        restart: unless-stopped
        links:
            - odoo$ODOO_MAJOR:www
        environment:
            STAGING: "false"
        networks:
            - back
            - front

    inbox:
        extends:
            file: common.yaml
            service: inboxreal
        restart: unless-stopped
        networks:
            - back

    smtp:
        extends:
            file: common.yaml
            service: smtpreal
        restart: unless-stopped
        networks:
            - back

    backup:
        extends:
            file: common.yaml
            service: backup
        restart: unless-stopped
        links:
            - db$ODOO_MAJOR:postgresdb
            - smtp
        volumes_from:
            - odoo$ODOO_MAJOR
        networks:
            - back

volumes:
    filestore$ODOO_MAJOR:
    db$ODOO_MAJOR:
    smtp:
    certs:
    certscron:

networks:
    back:
    front:
