version: "2.1"
services:
    odoo10:
        extends:
            file: common.yaml
            service: odoo
        build:
            args:
                # You may want demo data for testing
                WITHOUT_DEMO: "no"
        environment:
            PGDATABASE: test
        links:
            - db10:db
            - inbox
            - smtp

    db10:
        extends:
            file: common.yaml
            service: db

    https:
        extends:
            file: common.yaml
            service: https
        links:
            - odoo10:www

    inbox:
        extends:
            file: common.yaml
            service: inboxfake

    smtp:
        extends:
            file: common.yaml
            service: smtpfake

volumes:
    filestore10:
    db10:
    certs:
    certscron:
