version: "2.1"
services:
    odoo:
        extends:
            file: common.yaml
            service: odoo
        build:
            args:
                PGDATABASE: test
                # You may want demo data for testing
                WITHOUT_DEMO: "false"
        depends_on:
            - db
            - smtp
            - inbox

    db:
        extends:
            file: common.yaml
            service: db

    https:
        extends:
            file: common.yaml
            service: https
        depends_on:
            - odoo

    inbox:
        extends:
            file: common.yaml
            service: inboxfake

    smtp:
        extends:
            file: common.yaml
            service: smtpfake

volumes:
    # XXX Odoo volume names must match $ODOO_MAJOR for quick branch switching
    filestore10:
    db10:
    certs:
    certscron:
