version: "2.1"
services:
    odoo10:
        extends:
            file: common.yaml
            service: odoo
        environment:
            PGDATABASE: test
        links:
            - db10:db
        volumes:
            - filestore10:/home/odoo/.local/share/Odoo

    db10:
        extends:
            file: common.yaml
            service: db
        volumes:
            - db10:/var/lib/postgresql/data

    https:
        build: https
        ports:
            # XXX Use static ports here if possible
            - "80"
            - "443"
        links:
            - odoo10:www
        environment:
            PORT: 8069
            # XXX Change these for your real data
            EMAIL: admin@example.com
            DOMAINS: test.example.com

    smtp:
        extends:
            file: common.yaml
            service: smtpfake

volumes:
    filestore10:
    db10:
