version: "2.1"
services:
    odoo$ODOO_MAJOR:
        extends:
            file: common.yaml
            service: odoo
        build:
            args:
                PGDATABASE: test
                # You may want demo data for testing
                WITHOUT_DEMO: "no"
        links:
            - db$ODOO_MAJOR:db
            - inbox
            - smtp

    db$ODOO_MAJOR:
        extends:
            file: common.yaml
            service: db

    https:
        extends:
            file: common.yaml
            service: https
        links:
            - odoo$ODOO_MAJOR:www

    inbox:
        extends:
            file: common.yaml
            service: inboxfake

    smtp:
        extends:
            file: common.yaml
            service: smtpfake

volumes:
    filestore$ODOO_MAJOR:
    db$ODOO_MAJOR:
    certs:
    certscron:
